backend:
  name: git-gateway
media_folder: src/images
public_folder: /images
collections:
  - label: Sider
    name: pages
    files: []
  - label: Nyheter
    name: nyheter
    folder: src/pages/nyheter/posts
    create: true
    fields:
      - { label: Tittel, name: title, widget: string }
      - { label: Blurb, name: blurb, widget: string }
      - { label: Publiseringsdato, name: date, widget: datetime }
      - label: Bilde
        name: image
        widget: object
        collapsed: false
        fields:
          - { label: Bilde, name: link, widget: image }
          - { label: Bildetekst, name: text, widget: string }
      - { label: Hoveddel, name: body, widget: markdown }
