backend:
  name: git-gateway
media_folder: src/images
public_folder: /images
collections:
  - label: Sider
    name: pages
    files:
      - label: Hjem
        name: index
        file: src/pages/home/index.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Velkommen
            name: welcome
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }
          - label: Påmelding
            name: signUp
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }
              - { label: Lenke, name: link, widget: string }
          - label: Nyheter
            name: news
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
          - label: Kontakt oss
            name: contact
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
          - label: Om oss
            name: hml
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Bilde, name: picture, widget: image }
              - { label: Innhold, name: text, widget: markdown }

      - label: Overnatting
        name: overnight
        file: src/pages/overnatting/overnatting.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
          - label: Overnattingssteder
            name: places
            widget: list
            fields:
              - { label: Navn, name: name, widget: string }
              - label: Email
                name: emails
                required: false
                widget: list
                field: { label: Email, name: email, widget: string }
              - label: Telefonnummer
                name: phoneNumbers
                required: false
                widget: list
                field:
                  { label: Telefonnummer, name: phoneNumber, widget: string }
              - label: Nettside
                name: website
                required: false
                widget: string
              - label: Adresse
                name: address
                required: false
                widget: object
                fields:
                  - { label: Tekst, name: text, widget: string }
                  - label: Breddegrad
                    name: latitude
                    widget: number
                    default: 0
                    value_type: float
                  - label: Lengdegrad
                    name: longitude
                    widget: number
                    default: 0
                    value_type: float
              - { label: Bilde, name: image, widget: image }
              - { label: Beskrivelse, name: description, widget: markdown }
              - { label: Sengeplasser, name: beds, widget: string }
              - { label: Pris, name: price, widget: string }
              - { label: Frokost, name: breakfast, widget: string }

      - label: Program
        name: program
        file: src/pages/program/program.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
          - label: Program
            name: program
            widget: list
            fields:
              - { label: Tittel, name: title, widget: string }
              - label: Hendelser
                name: events
                widget: list
                fields:
                  - { label: Tid, name: time, widget: string }
                  - { label: Tittel, name: title, widget: string }
                  - { label: Beskrivelse, name: description, widget: markdown }

      - label: Arenaer
        name: arenas
        file: src/pages/arenaer/arenaer.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
          - label: Arenaer
            name: arenas
            widget: list
            fields:
              - { label: Navn, name: name, widget: string }
              - { label: Bilde, name: image, widget: image }
              - { label: Beskrivelse, name: description, widget: markdown }
              - label: Email
                name: emails
                widget: list
                field: { label: Email, name: email, widget: string }
              - label: Telefonnummer
                name: phoneNumbers
                widget: list
                field:
                  { label: Telefonnummer, name: phoneNumber, widget: string }
              - { label: Nettside, name: website, widget: string }
              - label: Adresse
                name: address
                widget: object
                fields:
                  - { label: Tekst, name: text, widget: string }
                  - label: Breddegrad
                    name: latitude
                    widget: number
                    default: 0
                    value_type: float
                  - label: Lengdegrad
                    name: longitude
                    widget: number
                    default: 0
                    value_type: float

      - label: Praktisk info
        name: practicalInfo
        file: src/pages/praktiskInfo/praktiskInfo.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
          - label: Kart
            name: map
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }
          - label: Taxi
            name: taxi
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }
          - label: Mat
            name: food
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }

      - label: Samarbeidspartnere
        name: partners
        file: src/pages/samarbeidspartnere/samarbeidspartnere.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
          - label: Samarbeidspartnere
            name: partners
            widget: list
            fields:
              - { label: Navn, name: name, widget: string }
              - { label: Logo, name: logo, widget: image }
              - { label: Nettside, name: website, widget: string }

  - label: Nyheter
    name: nyheter
    folder: src/pages/nyheter/posts
    create: true
    fields:
      - { label: Tittel, name: title, widget: string }
      - { label: Blurb, name: blurb, widget: string }
      - { label: Publiseringsdato, name: date, widget: datetime }
      - label: Bilde
        name: image
        widget: object
        collapsed: false
        fields:
          - { label: Bilde, name: link, widget: image }
          - { label: Bildetekst, name: text, widget: string }
      - { label: Hoveddel, name: body, widget: markdown }

  - label: Data
    name: data
    files:
      - label: Generelt
        name: general
        file: src/_data/site.json
        fields:
          - label: Navigasjon
            name: nav
            widget: list
            fields:
              - { label: Navn, name: name, widget: string }
              - { label: Link, name: link, widget: string }
          - label: Kontakt
            name: contact
            widget: object
            fields:
              - { label: Email, name: email, widget: string }
              - { label: Facebook, name: facebookPage, widget: string }
              - { label: Telefonnummer, name: phoneNumber, widget: string }
