backend:
  name: git-gateway
media_folder: src/images
public_folder: /images
collections:
  - label: Sider
    name: pages
    files:
      - label: Program
        name: program
        file: src/pages/program/program.yaml
        fields:
          - label: Sidetittel
            name: pageTitle
            widget: string
          - label: Innledning
            name: lead
            widget: object
            fields:
              - label: Tittel
                name: title
                widget: string
              - label: Tekst
                name: text
                widget: markdown
          - label: Program
            name: program
            widget: list
            fields:
              - label: Tittel
                name: title
                widget: string
              - label: Hendelser
                name: events
                widget: list
                fields:
                  - label: Tid
                    name: time
                    widget: string
                  - label: Tittel
                    name: title
                    widget: string
                  - label: Beskrivelse
                    name: description
                    widget: markdown

      - label: Hjem
        name: index
        file: src/pages/home/index.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Velkommen
            name: welcome
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }
          - label: Påmelding
            name: signUp
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Innhold, name: content, widget: markdown }
              - { label: Lenke, name: link, widget: string }
          - label: Nyheter
            name: news
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
          - label: Kontakt oss
            name: contact
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
          - label: Om oss
            name: hml
            widget: object
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Bilde, name: picture, widget: image }
              - { label: Innhold, name: text, widget: markdown }

  - label: Nyheter
    name: nyheter
    folder: src/pages/nyheter/posts
    create: true
    fields:
      - { label: Tittel, name: title, widget: string }
      - { label: Blurb, name: blurb, widget: string }
      - { label: Publiseringsdato, name: date, widget: datetime }
      - label: Bilde
        name: image
        widget: object
        collapsed: false
        fields:
          - { label: Bilde, name: link, widget: image }
          - { label: Bildetekst, name: text, widget: string }
      - { label: Hoveddel, name: body, widget: markdown }
