backend:
  name: git-gateway
media_folder: src/images
collections:
  - label: Sider
    name: pages
    files:
      - label: Om oss
        name: omOss
        file: src/pages/omOss/omOss.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            collapsed: false
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
  - label: Nyheter
    name: nyheter
    folder: src/pages/nyheter/posts
    create: true
    fields:
      - { label: Tittel, name: title, widget: string }
      - { label: Blurb, name: blurb, widget: string }
      - { label: Publiseringsdato, name: date, widget: datetime }
      - label: Bilde
        name: image
        widget: object
        collapsed: false
        fields:
          - { label: Bilde, name: link, widget: image }
          - { label: Bildetekst, name: text, widget: string }
      - { label: Hoveddel, name: body, widget: markdown }
