backend:
  name: git-gateway
media_folder: src/images
collections:
  - label: Sider
    name: pages
    files:
      - label: Om oss
        name: omOss
        file: src/pages/omOss/omOss.yaml
        fields:
          - { label: Sidetittel, name: pageTitle, widget: string }
          - label: Innledning
            name: lead
            widget: object
            collapsed: false
            fields:
              - { label: Tittel, name: title, widget: string }
              - { label: Tekst, name: text, widget: markdown }
